version: "3.8"
services:
  backend:
    build: .
    ports:
      - "4000:4000"
    env_file: .env
    volumes:
      - repos-data:/app/src/repos
      - ./src:/app/src
    depends_on:
      - redis

  redis:
    image: redis:alpine

volumes:
  repos-data:
